import type { Place } from './prospects'

/** Made-up El Paso businesses for demo mode (shown with a "Sample results" banner). */
const base = { primaryType: null, typeLabel: null, types: [], priceLevel: 2, website: null, mapsUrl: null, openNow: true, status: 'OPERATIONAL', servesBrunch: null, servesBreakfast: null, servesVegetarian: null, servesCocktails: null, summary: null }
type SamplePlace = Place & { searchTypes: string[] }
const P = (p: Partial<Place> & Pick<Place, 'id' | 'name' | 'address' | 'lat' | 'lng'>, searchTypes: string[]): SamplePlace => ({ ...base, rating: 4.4, reviews: 120, phone: null, ...p, searchTypes })

const ALL = ['restaurants', 'taquerias', 'mexican', 'brunch', 'bars', 'cafes', 'juice', 'food_trucks', 'bakeries', 'catering', 'hotels', 'markets', 'gyms', 'cafeterias', 'ghost_kitchens']

export const SAMPLE_PLACES: SamplePlace[] = [
  P({ id: 'sample-1', name: 'Tacos La Güera', address: '3800 Montana Ave, El Paso, TX', lat: 31.7801, lng: -106.4532, primaryType: 'mexican_restaurant', typeLabel: 'Mexican restaurant', types: ['mexican_restaurant', 'restaurant'], rating: 4.6, reviews: 486, phone: '(915) 555-0141', priceLevel: 1, summary: 'Street tacos with fresh salsa bar and pico' }, ['restaurants', 'taquerias', 'mexican']),
  P({ id: 'sample-2', name: 'Mariscos El Faro', address: '7100 Alameda Ave, El Paso, TX', lat: 31.7228, lng: -106.3567, primaryType: 'seafood_restaurant', typeLabel: 'Seafood restaurant', types: ['seafood_restaurant', 'mexican_restaurant'], rating: 4.5, reviews: 312, phone: '(915) 555-0142', summary: 'Ceviche, cocteles and mariscos' }, ['restaurants', 'mexican']),
  P({ id: 'sample-3', name: 'Green Press Juicery', address: '5800 N Mesa St, El Paso, TX', lat: 31.8311, lng: -106.5482, primaryType: 'juice_shop', typeLabel: 'Juice shop', types: ['juice_shop', 'cafe'], rating: 4.8, reviews: 38, phone: '(915) 555-0143', website: 'https://example.com', summary: 'Smoothie bowls and fresh juice' }, ['juice', 'cafes']),
  P({ id: 'sample-4', name: 'Sunrise Skillet', address: '9200 Dyer St, El Paso, TX', lat: 31.8741, lng: -106.4321, primaryType: 'breakfast_restaurant', typeLabel: 'Breakfast restaurant', types: ['breakfast_restaurant', 'brunch_restaurant'], rating: 4.4, reviews: 640, phone: '(915) 555-0144', servesBrunch: true }, ['restaurants', 'brunch']),
  P({ id: 'sample-5', name: 'The Union Taproom', address: '300 S Kansas St, El Paso, TX', lat: 31.7578, lng: -106.4852, primaryType: 'bar', typeLabel: 'Bar', types: ['bar', 'pub'], rating: 4.3, reviews: 255, phone: '(915) 555-0145', servesCocktails: true, openNow: false }, ['bars']),
  P({ id: 'sample-6', name: 'Café Mesa Verde', address: '1600 N Mesa St, El Paso, TX', lat: 31.7712, lng: -106.4987, primaryType: 'coffee_shop', typeLabel: 'Coffee shop', types: ['coffee_shop', 'cafe'], rating: 4.7, reviews: 190, phone: '(915) 555-0146', summary: 'Coffee, pastries and salads' }, ['cafes', 'brunch']),
  P({ id: 'sample-7', name: 'Panadería La Estrella', address: '8000 Alameda Ave, El Paso, TX', lat: 31.7155, lng: -106.3471, primaryType: 'bakery', typeLabel: 'Bakery', types: ['bakery'], rating: 4.6, reviews: 410, phone: '(915) 555-0147', priceLevel: 1 }, ['bakeries']),
  P({ id: 'sample-8', name: 'Borderland Catering Co.', address: '1400 Lee Trevino Dr, El Paso, TX', lat: 31.7738, lng: -106.3361, primaryType: 'catering_service', typeLabel: 'Caterer', types: ['catering_service'], rating: 4.9, reviews: 64, phone: '(915) 555-0148' }, ['catering']),
  P({ id: 'sample-9', name: 'FitLab El Paso', address: '11800 Montwood Dr, El Paso, TX', lat: 31.7634, lng: -106.2532, primaryType: 'gym', typeLabel: 'Gym', types: ['gym', 'health'], rating: 4.7, reviews: 220, phone: '(915) 555-0149' }, ['gyms']),
  P({ id: 'sample-10', name: 'Taco Bell', address: '5300 N Mesa St, El Paso, TX', lat: 31.8254, lng: -106.5421, primaryType: 'fast_food_restaurant', typeLabel: 'Fast food', types: ['fast_food_restaurant'], rating: 3.8, reviews: 900, phone: '(915) 555-0150', priceLevel: 1 }, ['restaurants', 'taquerias', 'mexican']),
  P({ id: 'sample-11', name: 'Poke Paradise', address: '7500 N Mesa St, El Paso, TX', lat: 31.8566, lng: -106.5745, primaryType: 'hawaiian_restaurant', typeLabel: 'Poke bar', types: ['restaurant'], rating: 4.5, reviews: 18, phone: '(915) 555-0151', summary: 'Fresh poke bowls and salads' }, ['restaurants']),
  P({ id: 'sample-12', name: 'El Rancho Market', address: '9400 Socorro Rd, Socorro, TX', lat: 31.6617, lng: -106.2814, primaryType: 'grocery_store', typeLabel: 'Grocery store', types: ['grocery_store', 'market'], rating: 4.2, reviews: 130, phone: '(915) 555-0152' }, ['markets']),
  P({ id: 'sample-13', name: 'Hotel Paso del Norte Grill', address: '10 Henry Trost Ct, El Paso, TX', lat: 31.7585, lng: -106.4891, primaryType: 'hotel', typeLabel: 'Hotel', types: ['hotel', 'restaurant'], rating: 4.6, reviews: 1500, phone: '(915) 555-0153', priceLevel: 3 }, ['hotels']),
  P({ id: 'sample-14', name: 'La Troca de Don Beto', address: '2500 N Zaragoza Rd, El Paso, TX', lat: 31.7891, lng: -106.3012, primaryType: 'food_truck', typeLabel: 'Food truck', types: ['food_truck', 'mexican_restaurant'], rating: 4.8, reviews: 95, phone: '(915) 555-0154' }, ['food_trucks', 'taquerias']),
  P({ id: 'sample-15', name: 'Upper Valley Kitchen', address: '5000 Doniphan Dr, El Paso, TX', lat: 31.8612, lng: -106.5893, primaryType: 'american_restaurant', typeLabel: 'Restaurant', types: ['american_restaurant', 'restaurant'], rating: 4.5, reviews: 350, phone: '(915) 555-0155', servesBrunch: true, servesVegetarian: true, summary: 'Farm-to-table plates and brunch' }, ['restaurants', 'brunch']),
  P({ id: 'sample-16', name: 'Casa Luna Cocina', address: '5860 N Mesa St, El Paso, TX', lat: 31.8327, lng: -106.5496, primaryType: 'mexican_restaurant', typeLabel: 'Mexican restaurant', types: ['mexican_restaurant'], rating: 4.6, reviews: 520, phone: '915-555-0101' }, ALL),
]
